/**
 * 所有在房间中会存在多个的建筑
 *
 * 可以直接通过例如 room[STRUCTURE_SPAWN] 获取到对应的对象**数组**
 */
export const MULTIPLE_STRUCTURES: AllRoomShortcut[] = [
  STRUCTURE_SPAWN,
  STRUCTURE_EXTENSION,
  STRUCTURE_ROAD,
  STRUCTURE_WALL,
  STRUCTURE_RAMPART,
  STRUCTURE_KEEPER_LAIR,
  STRUCTURE_PORTAL,
  STRUCTURE_LINK,
  STRUCTURE_TOWER,
  STRUCTURE_LAB,
  STRUCTURE_CONTAINER,
  "source"
];
